apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "airops.fullname" . }}-api
  labels:
    {{- include "airops.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      {{- include "airops.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        {{- include "airops.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api
        lab.vulnkube.io/vulnerable: "true"
      annotations:
        lab.vulnkube.io/vulnerabilities: {{ join "," .Values.lab.enabledVulnerabilities | quote }}
    spec:
      serviceAccountName: {{ include "airops.fullname" . }}-api
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: 4000
              name: http
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "airops.fullname" . }}-secrets
                  key: database-url
            - name: REDIS_URL
              value: redis://{{ include "airops.fullname" . }}-redis:6379
            - name: S3_ENDPOINT
              value: http://{{ include "airops.fullname" . }}-minio:9000
            - name: S3_BUCKET
              value: {{ .Values.minio.bucket | quote }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "airops.fullname" . }}-secrets
                  key: minio-root-user
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "airops.fullname" . }}-secrets
                  key: minio-root-password
            - name: ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "airops.fullname" . }}-secrets
                  key: admin-token
            - name: LAB_OPERATORS
              value: {{ toJson .Values.lab.operators | quote }}

            - name: KEYCLOAK_BASE_URL
              value: http://{{ include "airops.fullname" . }}-keycloak:{{ .Values.keycloak.service.port }}/auth

            - name: KEYCLOAK_REALM
              value: {{ .Values.keycloak.realm | quote }}

            - name: KEYCLOAK_CLIENT_ID
              value: {{ .Values.keycloak.clientId | quote }}

            - name: KEYCLOAK_CLIENT_SECRET
              value: {{ .Values.keycloak.clientSecret | quote }} # TODO : pas bien 

          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources.api | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "airops.fullname" . }}-api
  labels:
    {{- include "airops.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  selector:
    {{- include "airops.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: http
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "airops.fullname" . }}-api
  labels:
    {{- include "airops.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
