apiVersion: v1
kind: Secret
metadata:
  name: {{ include "airops.fullname" . }}-secrets
  labels:
    {{- include "airops.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-password: {{ .Values.postgresql.auth.password | quote }}
  database-url: {{ printf "postgres://%s:%s@%s-postgresql:5432/%s" .Values.postgresql.auth.username .Values.postgresql.auth.password (include "airops.fullname" .) .Values.postgresql.auth.database | quote }}
  minio-root-user: {{ .Values.minio.auth.rootUser | quote }}
  minio-root-password: {{ .Values.minio.auth.rootPassword | quote }}
  admin-token: {{ .Values.api.env.adminToken | quote }}
  openldap-admin-password: {{ .Values.openldap.adminPassword | quote }}
  keycloak-admin-password: {{ .Values.keycloak.admin.password | quote }}
  keycloak-db-password: {{ .Values.keycloak.db.password | quote }}
