global:
  imagePullPolicy: IfNotPresent
  hostname: "192.168.10.252"

api:
  image:
    repository: vulnkube/airops-api
    tag: local

frontend:
  image:
    repository: vulnkube/airops-frontend
    tag: local

caddy:
  service:
    type: NodePort
    port: 80
    nodePort: 30080

keycloak:
  ingressPath: /auth

  admin:
    username: admin
    password: admin

  db:
    username: keycloak
    password: keycloak
    database: keycloak

  service:
    port: 8080

  realm: airops
  clientId: airops-backend
  clientSecret: airops-backend-secret-change-me

ingress:
  enabled: true
  className: traefik
  path: /
  annotations: {}

bookstack:
  appKey: "base64:7N5PrQg2rgg5kxQq47lmOhcOiA+qnOs7coHGuhuMATc="
  ingresPath: "bookstack"
  service:
    port: 80
  db:
    username: bookstack
    password: "C2Xe8PykNH8VojW9P9aIOnbbKp49j5MD"
    database: bookstack
  mysql:
    persistence:
      size: 5Gi
