global:
  imagePullPolicy: IfNotPresent
  hostname: "192.168.10.252"

api:
  image:
    repository: vulnkube/airops-api
    tag: local

frontend:
  image:
    repository: vulnkube/airops-frontend
    tag: local

caddy:
  service:
    type: NodePort
    port: 80
    nodePort: 30080

keycloak:
  ingressPath: /auth

  admin:
    username: admin
    password: admin

  db:
    username: keycloak
    password: keycloak
    database: keycloak

  service:
    port: 8080

  realm: airops
  clientId: airops-backend
  clientSecret: airops-backend-secret-change-me

ingress:
  enabled: true
  className: traefik
  path: /
  annotations: {}
