global:
  imagePullPolicy: IfNotPresent

api:
  image:
    repository: vulnkube/airops-api
    tag: local

frontend:
  image:
    repository: vulnkube/airops-frontend
    tag: local

caddy:
  service:
    type: NodePort
    port: 80
    nodePort: 30080

keycloak:
  ingressPath: /auth

  admin:
    username: admin
    password: admin

  db:
    username: keycloak
    password: keycloak
    database: keycloak

  service:
    port: 8080

ingress:
  enabled: true
  className: traefik
  path: /
  annotations: {}
