{{- if .Values.keycloak.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "airops.fullname" . }}-keycloak
  labels:
    {{- include "airops.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
spec:
  selector:
    {{- include "airops.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
  ports:
    - name: http
      port: {{ .Values.keycloak.service.port }}
      targetPort: http
{{- end }}
